### ISSUE TITLE
0.6.4 fails to compile

### ISSUE THREAD

**Issue by binaryape** [annkissam/common_graphql_client#28]
Hi,

I can't get a Phoenix app using Common Graphql Client 0.6.4 to compile - it produces this error:

```elixir 
warning: variable "opts" does not exist and is being expanded to "opts()", please use parentheses to remove the ambiguity or change the variable name
  lib/common_graphql_client/client.ex:236: Multiverse.Loader.Client.connection/1


== Compilation error in file lib/multiverse/loader/client.ex ==
** (CompileError) lib/common_graphql_client/client.ex:236: undefined function opts/0
    (elixir 1.12.1) src/elixir_locals.erl:114: anonymous fn/3 in :elixir_locals.ensure_no_undefined_local/3
    (stdlib 3.15) erl_eval.erl:685: :erl_eval.do_apply/6
    (elixir 1.12.1) lib/kernel/parallel_compiler.ex:319: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/7
```

If I switch back to version 0.6.3 everything works again.

I'm using Erlang 24 and Elixir 12.1.

I haven't had enough time to investigate properly yet - sorry about the lack of details.

Pete

**Comment by Rodeoclash** [comment]
I can confirm I'm seeing this as well
